In [1]:
import numpy as np
from IPython.display import Image

In [2]:
arr = np.arange(0, 32)
print(arr)
print(type(arr))
print(arr.shape) # 데이터 속성 (32,) 이렇게 나오는데 이게 1차원 이라는 뜻

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
<class 'numpy.ndarray'>
(32,)


In [3]:
# reshape() 함수는 numpy 배열의 차원을 변경한다.
v = arr.reshape(4,2,4) # reshape(면,행,열) # 근데 여기서 면행열의 곱은 그 arr의 개수와 같아야 한다.
t = arr.reshape(4,1,8)
print(v)
print(t)
print(v.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
[[[ 0  1  2  3  4  5  6  7]]

 [[ 8  9 10 11 12 13 14 15]]

 [[16 17 18 19 20 21 22 23]]

 [[24 25 26 27 28 29 30 31]]]
(4, 2, 4)


numpy의 sum() 함수의 작동방식

In [4]:
# sum() 함수의 axis 속성의 기본값은 'None'(축이 없다.)이고, axis는 대상 데이터의 차원보다 작은 값을 설정한다.
# 위의 예제 데이터의 차원이 3이기 때문에 axis 속성은 2까지 지정할 수 있다.
print(v.ndim) # ndim: numpy 배열의 차원(Dimension)을 얻어온다.

3


In [5]:
# axis = None
# axis를 기본값으로 실행하면 대상 데이터의 모든 요소의 합계를 계산해 리턴한다.
# 대상 데이터에 포함된 모든 요소를 단순하게 합산하는 연산이 실행 된다.
print(v.shape)
print(v.sum())
print(v.sum(axis=None))

(4, 2, 4)
496
496


In [6]:
# axis=0
# axis=0는 x축을 기준으로 계산한 합계를 리턴한다.
# shape이 (4,2,4)인 데이터의 x축을 기준으로 합계를 계산하고 결과 shape은 면이 제거되고 (2,4)이 리턴된다.
# 위에서 쭉 누른 느낌
result = v.sum(axis=0)
print(result)
print(result.shape)
print(result.ndim)

[[48 52 56 60]
 [64 68 72 76]]
(2, 4)
2


In [8]:
# axis=0은 가장 외곽의 괄호를 제거하는 이미지를 생각하면 된다.
# 아래 그림 처럼(영상을 보던 선생님 코드를 가져오던) 가장 외곽에

In [9]:
# axis = 1
# axis = 1은 y축을 기준으로 계산한 합계를 리턴 한다.
# shape이 (4,2,4)인 데이터를 y축을 기준으로 합계를 계산하고 결과 shape은 행이 제거되고 (4,4)가 리턴 된다.
result = v.sum(axis=1)
print(result)
print(result.shape)
print(result.ndim)

[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]
(4, 4)
2


In [ ]:
# axis = 1 은 가장 안쪽에서 두번째 (4,2,4)중에서 순서대로 0 ,1, 2 라고 생각하면 된다.
# 가장 외곽의 두번째 괄호를 제거하고 각 행의 데이터는 위치별로 합계를 계산한다.
# 그런데 이거 이해 하려면 녹화영상을 꼭 한번 더 봐라
# 이게 그림을 보면 알겠지만
# 3차 그래프를 그릴때 x축 y축 z축 방향을 화살표로 그리잖아
# 그 방향대로 겹쳐진다고 생각하면 좀 이해 될듯

In [10]:
# axis=2
# axis=2는 z축을 기준으로 계산한 합계를 리턴한다.
# shape이 (4,2,4)인 데이터를 z축을 기준으로 합계를 계산하고 결과 shape은 열이 제거되고 (4,2)가 리턴된다.
# 가장 안쪽 괄호를 제거하는 이미지를 생각하면 된다.
result = v.sum(axis=2)
print(result)
print(result.shape)
print(result.ndim)

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]
(4, 2)
2
