In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape,arr.ndim,arr.dtype))
    print('numpy 배열에 저장된 데이터\n',arr)

numpy 배열 파일 입출력

In [3]:
# numpy는 배열 객체를 바이너리 파일 또는 텍스트 파일에 저장하고 로딩하는 기능을 제공한다.
# 메소드 이름    기능                                               파일포맷
# np.save()      numpy 배열 객체 1개를 파일에 저장한다.              바이너리 => 얘들은 넘파이 전용 파일이다, 텍스트 보다 읽는 속도가 빠르다.
# np.savez()     numpy 배열 객체 여러개를 파일에 저장한다.           바이너리 => 바이너리 파일은 우리가 읽을 수 없다.
# np.load()      numpy 배열 저장 파일로 부터 객체를 읽어온다.        바이너리
# np.savetxt()   numpy 배열 객체를 텍스트 파일에 저장한다.           텍스트 => txt(x), csv(o), tsv(o)
# np.loadtxt()   텍스트 파일에 저장된 numpy 배열 객체를 읽어온다.     텍스트 => 텍스트는 어디에서든지 호환이 가능하다.

In [5]:
np.random.seed(100)
a= np.random.randint(0,10,(2,3))
pprint(a)
b= np.random.randint(0,10,(2,3))
pprint(b)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[8 8 3]
 [7 7 0]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[4 2 5]
 [2 2 2]]


In [7]:
# 배열 객체 저장 - 바이너리 파일
# np.save(), np.savez() 함수를 이용해서 배열 객체를 바이너리(2진) 형태의 파일로 저장할 수 있다.
# np.save() : 배열 1개를 저장한다. (확장명 => npy(넘파이))
# np.savez() : 배열 여러개를 저장한다. (확장명 => npz)

# a 배열을 파일로 저장한다.
# 현재 소스파일이 있는 폴더를 => [ . ] 로 나타낸다.
# 확장명은 써주지 않아도 된다 알아서 붙는다.
np.save('./output/my_array1',a)

# a,b 배열을 파일로 저장한다.
np.savez('./output/my_array2',a,b)

In [9]:
# np.load() 함수로 npy, npz 파일로 부터 배열 데이터를 읽어 올 수 있다. 확장명을 반드시 적어야 한다.
# npy 파일 읽기
print(np.load('./output/my_array1.npy'))
# npz 파일 읽기
print(np.load('./output/my_array2.npz'))
# 주소에 생성되어 있던 객체를 받아줄 npzFile 이라는 변수를 만든다
# npz는 파일이 여러개여서 그런듯
npzFile = np.load('./output/my_array2.npz')
# 이렇게 배열처럼 뽑아 낸다.
print(npzFile['arr_0'])
print(npzFile['arr_1'])

[[8 8 3]
 [7 7 0]]
[[8 8 3]
 [7 7 0]]
[[4 2 5]
 [2 2 2]]


In [10]:
data = np.random.random((3,4))
pprint(data)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: float64
numpy 배열에 저장된 데이터
 [[0.13670659 0.57509333 0.89132195 0.20920212]
 [0.18532822 0.10837689 0.21969749 0.97862378]
 [0.81168315 0.17194101 0.81622475 0.27407375]]


In [12]:
# 배열 객체 저장 - 텍스트 파일
# np.savetxt() 함수로 배열 객체를 텍스트 파일로 저장 할 수 있다. => csv파일, tsv 파일
# np.savetxt('파일 이름', 데이터, delimiter='구분자' ) # 구분자가 ,면 csv  \t(텝)이면 tsv

# data 배열을 텍스트 파일로 저장한다.
# 확장명을 반드시 적어야 제대로 생긴다.
# np.savetxt('./output/saved.csv',data)
np.savetxt('./output/saved.csv',data,delimiter=',') # 위에랑 똑같다.

np.savetxt('./output/saved.tsv',data,delimiter='\t')

배열(행렬) 연산 - 산술연산

In [16]:
a= np.arange(1,10).reshape(3,3) # reshape으로 형태를 바꿔줌
pprint(a)

b = np.arange(9,0,-1).reshape(3,3) # reshape으로 형태를 바꿔줌
pprint(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [19]:
# 덧셈 : +, np.add()
pprint(a+b)
pprint(np.add(a,b)) # 둘다 똑같은 거다.

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [20]:
# 뺄셈 : -, np.subtract
pprint(a-b)
pprint(np.subtract(a,b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [21]:
# 곱셈 : *, np.multiply()  // 이거 배열 개수 곱셈이 아니라 배열에 값 각각 하는거 알지?
pprint(a*b)
pprint(np.multiply(a,b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [23]:
# 나눗셈 : /, // , np.divide(), %
pprint(a//b)
pprint(np.divide(a,b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[0 0 0]
 [0 1 1]
 [2 4 9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: float64
numpy 배열에 저장된 데이터
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [24]:
# 지수
print(np.exp(a))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [25]:
# 제곱근(루트)
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [27]:
# 삼각함수
print(np.cos(a))
print(np.sin(a))
print(np.tan(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [28]:
# 로그
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [29]:
# 행렬의 내적
pprint(np.dot(a,b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


비교연산

In [31]:
# 배열 요소별 비교 : >, >=, < .. 등등등
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [36]:
# 배열 통째로 비교
# np.array_equal() 함수를 사용하면 배열 전체를 비교할 수 있다.
# 모든 요소가 같아야 하고 하나라도 다르면 false가 나온다.
print(np.array_equal(a,b))

False


집계 함수

In [37]:
# 넘파이의 거의 모든 집계 함ㅅ는 axis를 기준으로 계산된다.
# 집계 함수에서 axis를 지정하지 않으면 axis=None이 기본값으로 사용된다.
# axis=Noen, axis=0, axis =1 과 같이 지정한다.

In [38]:
a= np.arange(1,10).reshape(3,3)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


합계 : 배열객체.sum(axis), np.sum(배열객체,axis)

In [40]:
# axis = None
# axis = None은 전체 배열을 하나의 배열로 간주하고 집계 함수의 범위전체 배열로 정의한다. 생략시 기본 값으로 사용된다.
print(a.sum())
print(a.sum(axis=None))
print(np.sum(a))
print(np.sum(a,axis=None))

45
45
45
45


In [41]:
# axis=0
# axis=0은 행을 기준으로 각 행의 동일한 인덱스 요소를 그룹으로 연산한다. => 각 열의 합계
print(a.sum(axis=0))
print(np.sum(a,axis=0))

[12 15 18]
[12 15 18]


In [42]:
# axis=1
# axis=1은 열을 기준으로 각 열의 동일한 인덱스 요소를 그룹으로 연산한다. => 각 행의 합계
print(a.sum(axis=1))
print(np.sum(a,axis=1))

[ 6 15 24]
[ 6 15 24]


최대값 : 배열객체.max(axis), np.max(배열객체,axis)  
최소값 : 배열객체.min(axis), np.min(배열객체,axis)

In [43]:
print(a.max())
print(a.max(axis=None))
print(np.max(a))
print(np.max(a,axis=None))

9
9
9
9


In [46]:
print(a.max(axis=0))
print(np.max(a,axis=0))
print(a.max(axis=1))
print(np.max(a,axis=1))

[7 8 9]
[7 8 9]
[3 6 9]
[3 6 9]


In [47]:
print(a.min())
print(a.min(axis=None))
print(np.min(a))
print(np.min(a,axis=None))

1
1
1
1


In [49]:
print(a.min(axis=0))
print(np.min(a,axis=0))
print(a.min(axis=1))
print(np.min(a,axis=1))

[1 2 3]
[1 2 3]
[1 4 7]
[1 4 7]


누적 합계 : 배열객체.cumsum(axis), np.cumsum(배열객체,axis)

In [50]:
# 첫번째는 1 더한거, 두번째는 1+2, 세번째는 1+2+3, 네번째 1+2+3+4  ... 이런식
print(a.cumsum())
print(a.cumsum(axis=None))
print(np.cumsum(a))
print(np.cumsum(a,axis=None))

[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]
[ 1  3  6 10 15 21 28 36 45]


In [51]:
# 열끼리 한줄씩 누적함
print(a.cumsum(axis=0))
print(np.cumsum(a,axis=0))
# 행끼리 한줄씩 누적함
print(a.cumsum(axis=1))
print(np.cumsum(a,axis=1))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


평균 : 배열객체.mean(axis),np.mean(axis)

In [52]:
print(a.mean())
print(a.mean(axis=None))
print(np.mean(a))
print(np.mean(a,axis=None))

5.0
5.0
5.0
5.0


In [53]:
print(a.mean(axis=0))
print(np.mean(a,axis=0))
print(a.mean(axis=1))
print(np.mean(a,axis=1))

[4. 5. 6.]
[4. 5. 6.]
[2. 5. 8.]
[2. 5. 8.]


중간값 : np.median(배열객체,axis)

In [54]:
# 중간값과 평균의 차이는 알지? 당연히 알아야 한다.
print(np.median(a,axis=None))
print(np.median(a,axis=0))
print(np.median(a,axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


표준편차 : 배열객체.std(axis), np.std(배열객체, axis)  
표준편차 => (값-평균)^2 / 개수 => 전체 루트값. // 루트 없으면 분산  
편차니까 (값-평균) 값으로 구하는거지

In [55]:
print(a.std())
print(a.std(axis=None))
print(np.std(a))
print(np.std(a,axis=None))

2.581988897471611
2.581988897471611
2.581988897471611
2.581988897471611


In [56]:
print(a.std(axis=0))
print(np.std(a,axis=0))
print(a.std(axis=1))
print(np.std(a,axis=1))

[2.44948974 2.44948974 2.44948974]
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]
[0.81649658 0.81649658 0.81649658]


브로드캐스팅 => 다대일 연산

In [57]:
# shape이 같은 두 배열에 이항 연산은 배열 요소별로 실행된다.
# 두 배열의 shape이 다를 경우 두 배열의 형상을 맞추는 아래 그림과 같은 브로드캐스팅 과정을 거쳐 실행된다.

shape이 같은 두 배열의 연산

In [60]:
a= np.arange(1,25).reshape(4,6)
pprint(a)
b = np.arange(25,49).reshape(4,6)
pprint(b)
# shape이 같은 두 배열을 이항 연산을 할 경우 위치가 같은 요소 단위로 실행 된다.
pprint(a+b)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]


shape이 다른 두 배열의 연산  
shape이 다른 두 배열 사이의 이항 연산에서 브로드캐스팅 발생 시 두 배열을 같은 shape으로 만든 후 연산을 실행한다.

In [61]:
# case 1 : 배열과 스칼라(단일 값)
# 배열과 스칼라 사이의 이항 연산시 스칼라를 배열로 변환한다.
a= np.arange(1,25).reshape(4,6)
pprint(a)
# 이런게 브로드캐스팅이다 -> 모든 값에 100이 더해지잖슴
pprint(a + 100)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [64]:
# a + 100은 다음과 같은 과정을 거쳐서 처리 된다.
# like를 쓰면 원본의 사이즈를 배껴 오잖아
# 그래서 저렇게 사이즈가 맞지 않으면 like를 내부적으로 불러서 사이즈 맞추고
# 그리고 더해지는 거다.
new_arr = np.full_like(a, 100)
pprint(new_arr)
pprint(a+new_arr)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [68]:
# case 2 : shape이 다른 배열의 연산
a= np.arange(5).reshape(1,5) # reshape을 안하면 보이게는 똑같아 보이지만, reshape을 하면 2차원이고, 안하면 1차원이다.
pprint(a)
b= np.arange(5).reshape(5,1)
pprint(b)
pprint(a+b)

type: <class 'numpy.ndarray'>
shape: (1, 5), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[0 1 2 3 4]]
type: <class 'numpy.ndarray'>
shape: (5, 1), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[0]
 [1]
 [2]
 [3]
 [4]]
type: <class 'numpy.ndarray'>
shape: (5, 5), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


벡터 연산

In [69]:
# 넘파이는 벡터 연산을 지원한다.
# 넘파이의 집합 연산에서는 벡터화 기능이 적용되어 있어서 배열 처리에 대해 연산을 적용할 경우 속도가 100배이상 빠르다.
# 머신러닝에서 선형대수 연산을 처리할 때 매우 높은 효과(효율)을 낼 수 있다.
a = np.arange(1,10000001,dtype=np.int64)

In [75]:
%%time
result = 0
for i in a:
    result += i
print(result)
# %%time 이거 주피터만 됨 시간재는거

50000005000000
Wall time: 5 s


In [78]:
%%time
result = np.sum(a) # 넘파이 연산은 벡터화 시키고 해서 연산 속도가 매우 빠르다.
print(result)

50000005000000
Wall time: 9.77 ms


배열 복사

In [79]:
# ndarray(넘파이로 만들어지는 배열 타입) 배열 객체에 대한 인덱싱, 슬라이싱(subset)이 반환하는 새로운 배열 객체가 아닌 원본 배열의 view이다.
# 반환된 배열이 값을 변경하면 원본 배열에 변경한 내용이 반영된다. => 원본과 사본이 같은 메모리를 사용한다.
# 따라서, 기본 배열로 부터 새로운 배열을 생성하기 위해서 copy() 함수를 사용한다.
# copy() 함수로 복사한 배열은 원본 배열과 완전히 다른 별도의 객체가 된다.

In [87]:
a = np.random.randint(0,9,(3,3))
pprint(a)

# 2차원 배열 슬라이싱
# 전체 행의 0번째 열
pprint(a[:,0])

b= a[:,0] # 이거 이렇게하면 배열 주소 공유한다.(같은 메모리 사용) 복사하는거 아님
b =np.array([999,999,999]) # 이렇게 새로 만들면 공유하지 않고 새로운 배열을 가르킴 
pprint(b)
pprint(a)
b= a[:,0]
a[:,0] = 999
pprint(a) # 슬라이싱만 바꿔도 배열이 바뀜 왜냐하면 슬라이싱을 새로 배열을 만드는게 아니라서 같은 메모리에 있는거를
# 잘라서 보여주는거이기 때문에

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[0 5 6]
 [6 5 6]
 [4 7 3]]
type: <class 'numpy.ndarray'>
shape: (3,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [0 6 4]
type: <class 'numpy.ndarray'>
shape: (3,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [999 999 999]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[0 5 6]
 [6 5 6]
 [4 7 3]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[999   5   6]
 [999   5   6]
 [999   7   3]]


In [92]:
copied_a = np.copy(a)
pprint(copied_a)
print(copied_a[:,1])
copied_a[:,1] = 777
print(copied_a[:,1])
pprint(copied_a) # 복사본은 바뀌지만
pprint(a) # 원본은 바뀌지 않음

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[999   5   6]
 [999   5   6]
 [999   7   3]]
[5 5 7]
[777 777 777]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[999 777   6]
 [999 777   6]
 [999 777   3]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[999   5   6]
 [999   5   6]
 [999   7   3]]


배열 정렬

In [94]:
# ndarray 객체는 axis를 기준으로 요소를 정렬하는 sort() 함수를 제공한다.
unsorted_arr = np.random.random((3,3))
pprint(unsorted_arr)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: float64
numpy 배열에 저장된 데이터
 [[0.68654496 0.43893494 0.97772095]
 [0.47738415 0.23895263 0.93235066]
 [0.13671513 0.17192781 0.50305449]]


In [95]:
# sort 작업을 위해 원본을 복사한다.
unsorted_arr1 = unsorted_arr.copy()
unsorted_arr2 = unsorted_arr.copy()
unsorted_arr3 = unsorted_arr.copy()

In [96]:
# 배열객체.sort()
# sort() 함수는 axis의 기본값이 None이 아니고 , -1이다.
# -1은 현재 배열의 마지막 axis를 의미하고, 즉 2 차원 배열은 마지막 axis는 1이니까 axis = 1을 의미한다.
# 배열객체.sort() 와 배열객체.sort(axis=-1) 와 배열객체.sort(axis=1)의 결과는 같다.

# 전체 통으로 정렬하는건 없다!

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: float64
numpy 배열에 저장된 데이터
 [[0.43893494 0.68654496 0.97772095]
 [0.23895263 0.47738415 0.93235066]
 [0.13671513 0.17192781 0.50305449]]


In [98]:
# 이렇게 하면 행대로 정렬된다.
unsorted_arr1.sort() 
pprint(unsorted_arr1)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: float64
numpy 배열에 저장된 데이터
 [[0.43893494 0.68654496 0.97772095]
 [0.23895263 0.47738415 0.93235066]
 [0.13671513 0.17192781 0.50305449]]


In [99]:
unsorted_arr2.sort(axis=-1) 
pprint(unsorted_arr2)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: float64
numpy 배열에 저장된 데이터
 [[0.43893494 0.68654496 0.97772095]
 [0.23895263 0.47738415 0.93235066]
 [0.13671513 0.17192781 0.50305449]]


In [101]:
unsorted_arr2.sort(axis=1) 
pprint(unsorted_arr2)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: float64
numpy 배열에 저장된 데이터
 [[0.43893494 0.68654496 0.97772095]
 [0.23895263 0.47738415 0.93235066]
 [0.13671513 0.17192781 0.50305449]]


In [102]:
# 열대로 정렬한다.
unsorted_arr1.sort(axis=0) 
pprint(unsorted_arr1)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: float64
numpy 배열에 저장된 데이터
 [[0.13671513 0.17192781 0.50305449]
 [0.23895263 0.47738415 0.93235066]
 [0.43893494 0.68654496 0.97772095]]
