In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape,arr.ndim,arr.dtype))
    print('numpy 배열에 저장된 데이터\n',arr)

인덱싱

In [2]:
# 배열의 각 요소는 axis 인덱스로 참조할 수 있다.
# 1차원 배열은 1개의 인덱스, 2차원 배열은 2개의 인덱스, 3차원 배열은 3개의 인덱스 로 참조할 수 있다.
# 인덱싱 작업시 [행][열]과 같이 인덱스를 지정하거나 [행,열]과 같이 인덱스를 지정할 수 있다.

In [3]:
a = np.arange(24)
pprint(a)
# 1차원 배열 요소 참조 및 변경
print(a[5])
a[5] = 100
pprint(a)

type: <class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
5
type: <class 'numpy.ndarray'>
shape: (24,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [  0   1   2   3   4 100   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]


In [4]:
# 2차원 배열
a=np.arange(24).reshape(4,6)
pprint(a)
# 2차원 배열 요소 참조 및 변경
print(a[0][1])
print(a[0, 1])
a[0][1] = 1000
pprint(a)
a[2][4] = 3333
pprint(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1
1
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[   0 1000    2    3    4    5]
 [   6    7    8    9   10   11]
 [  12   13   14   15   16   17]
 [  18   19   20   21   22   23]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[   0 1000    2    3    4    5]
 [   6    7    8    9   10   11]
 [  12   13   14   15 3333   17]
 [  18   19   20   21   22   23]]


In [5]:
# 3차원 배열
a=np.arange(24).reshape(2,4,3)
pprint(a)
# 3차원 배열 요소 참조 및 변경
print(a[0][2][1])
print(a[1,1,2])
a[0][2][1]=777
a[1,1,2]= 888
pprint(a)

type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열에 저장된 데이터
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
7
17
type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension: 3, dtype: int32
numpy 배열에 저장된 데이터
 [[[  0   1   2]
  [  3   4   5]
  [  6 777   8]
  [  9  10  11]]

 [[ 12  13  14]
  [ 15  16 888]
  [ 18  19  20]
  [ 21  22  23]]]


슬라이싱

In [6]:
# 1차원 배열 슬라이싱
a = np.arange(24)
print(a)
print(a[2:6])
print(a[:6])
print(a[2:])
print(a[:])
print(a[::2])
print(a[::-1]) # 반대로

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[2 3 4 5]
[0 1 2 3 4 5]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [7]:
# 2차원 배열 슬라이싱
b=np.arange(1,25).reshape(4,6)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [8]:
# 2차원 배열을 슬라이싱 할 때 행과 열 모두 슬라이싱 하려면 [] 내부에 행과 열을 모두 적어주어야 한다.
# b[1:3][1:5] 이런식으로 따로따로 하면 안된다는 뜻이다.
# 슬라이싱 작업시 []를 연속해서 사용하면 앞의 슬라이싱 결과를 가져와 뒤의 슬라이싱을 한다.
# 각각 따로 슬라이싱 한다는 뜻이다. 즉 행단위를 2번하는 결과가 나오게 된다.
# 따라서 [행,열]과 같은 방식을 사용해야 한다.  

pprint(b[1:3]) # 행만 슬라이싱 -> 행 단위로 슬라이싱 하려면 열을 생략한다.
pprint(b[:,1:5]) # 열만 슬라이싱 -> 열 단위로 슬라이싱 하려면 행을 생략한다. 
                    # -> 행에 행전체를 뜻하는':'을 써야한다. -> 행단위 슬라이싱과 구분하기 위해서
pprint(b[1:3,1:5]) # 전체 슬라이싱

type: <class 'numpy.ndarray'>
shape: (2, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
type: <class 'numpy.ndarray'>
shape: (4, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]]
type: <class 'numpy.ndarray'>
shape: (2, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 8  9 10 11]
 [14 15 16 17]]


In [9]:
# 슬라이싱에 음수 값이 있을 때는 음수값의 위치를 직접 찾고 하는게 이해하기 좋다.
# 음수 인덱싱을 이용한 범위 설정
# 음수 인덱스는 지정한 axis의 마지막 요소로부터 반대 방향의 인덱스이고 -1은 마지막 요소의 인덱스를 의미한다.
pprint(b[1:-1, 1:-1])

type: <class 'numpy.ndarray'>
shape: (2, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 8  9 10 11]
 [14 15 16 17]]


In [10]:
# 슬라이싱을 이용한 데이터 수정
pprint(b)
slide_arr = b[1:3, 1:5]
pprint(slide_arr)
pprint(slide_arr[:,1:3])
# 슬라이싱의 결과는 원본의 view이므로 슬라이싱 결과를 수정하면 원본이 바뀌지 않는다
slide_arr[:,1:3]=9999
pprint(slide_arr)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type: <class 'numpy.ndarray'>
shape: (2, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 8  9 10 11]
 [14 15 16 17]]
type: <class 'numpy.ndarray'>
shape: (2, 2), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 9 10]
 [15 16]]
type: <class 'numpy.ndarray'>
shape: (2, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[   8 9999 9999   11]
 [  14 9999 9999   17]]


불린 인덱싱 => 전체 데이터에서 특정 조건에 만족하는 데이터를 추출할 경우 많이 사용된다.  
넘파이의 불린 인덱싱은 각 배열 요소 선택 여부를 True, False로 지정하는 방식이다 => True를 선택한다.

In [11]:
a=np.arange(1,25).reshape(4,6)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [12]:
# a 배열에서 요소의 값이 짝수인 요소의 총 합계
even_arr = a % 2  # <= 브로드캐스팅 arr = a +100 이랑 같은거다.
print(even_arr)
even_arr1 = a % 2 == 0 # <= 얘는 조건식 까지 브로드캐스팅 했으므로 boolean 타입이 된다.
print(even_arr1)

[[1 0 1 0 1 0]
 [1 0 1 0 1 0]
 [1 0 1 0 1 0]
 [1 0 1 0 1 0]]
[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [13]:
# 브로드캐스팅을 통한 불린 인덱싱 => True인것만 추출
print(a[even_arr1])
print(a[a % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [14]:
print(a[even_arr1].sum())
print(a[a%2!=0].sum())

156
144


불린 인덱싱 응용

In [15]:
# pandas
import pandas as pd
# 데이터 파일 => 2014년 시애틀 강수량 데이터 => ./data/Seattle2014.csv
df=pd.read_csv('data/Seattle2014.csv')
df.head(10)

STATION                                STATION_NAME      DATE  \
0  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140101   
1  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140102   
2  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140103   
3  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140104   
4  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140105   
5  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140106   
6  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140107   
7  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140108   
8  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140109   
9  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140110   

   PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  WDF5  WSF2  WSF5  WT01  WT05  \
0     0     0     0    72    33    12   340   310    36    40 -9999 -9999   
1    41     0     0   106    61    32   190   200    94   116 -9999 -9999   
2    15     0     0    89    28    26    30    50    63    72     1 -9999   
3     0     0     0    78     6    27    40    40    45    58     1 -9999   
4     0     0     0    83    -5    37    10    10    67    76 -9999 -9999   
5     3     0     0    78    -5    26   210   210   112   125     1 -9999   
6   122     0     0    83    50    16   160   150    45    54 -9999 -9999   
7    97     0     0   100    72    46   180   180   107   143     1 -9999   
8    58     0     0    94    56    63   210   230   143   183     1 -9999   
9    43     0     0   128    83    70   200   200   134   183 -9999 -9999   

   WT02  WT03  
0 -9999 -9999  
1 -9999 -9999  
2 -9999 -9999  
3 -9999 -9999  
4 -9999 -9999  
5 -9999 -9999  
6 -9999 -9999  
7 -9999 -9999  
8 -9999 -9999  
9 -9999 -9999

In [16]:
# 2014년 시애틀 강수량 데이터의 강수량 열(PRCP)의 데이터만 추출한다.
rain_arr = df['PRCP'].values # pandas Series 데이터에 values 속성을 지정하면 넘파이 배열로 변환된다.
print(type(rain_arr))
print(rain_arr.shape)
print(rain_arr.ndim)
print(rain_arr)
print('Data size : {}'.format(len(rain_arr)))
print('Data size : {}'.format(rain_arr.size)) # 위에랑 같은거

<class 'numpy.ndarray'>
(365,)
1
[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23  20   0   0   0   0
   0   0  51   5 183 170  46  18  94 117 264 145 152  10  30  28  25  61
 130   3   0   0   0   5 191 107 165 467  30   0 323  43 188   0   0   5
  69  81 277   3   0   5   0   0   0   0   0  41  36   3 221 140   0   0
   0   0  25   0  46   0   0  46   0   0   0   0   0   0   5 109 185   0
 137   0  51 142  89 124   0  33  69   0   0   0   0   0 333 160  51   0
   0 137  20   5   0   0   0   0   0   0   0   0   0   0   0   0  38   0
  56   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  18  64   0   5  36  13   0   8   3   0   0   0   0   0   0  18  23   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   3 193   0   0   0   0   0   0   0   0   0   5   0   0
   0   0   0   0   0   0   5 127 216   0  10   0   0   0   0   0   0   0
   0   0   0   0  

In [17]:
days_arr = np.arange(1,366)
condition_jan = days_arr <= 31 # 1월의 날수 만큼 불린 인덱스 생성
print(condition_jan)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [18]:
# 불린 인덱싱을 이용해서 1월의 강수량만 추출한다.
rain_jan = rain_arr[condition_jan]
print(len(rain_jan))
print(rain_jan)

31
[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]


팬시 인덱싱  
배열에 인덱스를 전달해 요소를 참조하는 방법

In [19]:
a= np.arange(1,25).reshape(4,6)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [20]:
print(a[0,0],a[1,1],a[2,2],a[3,3])
a1 =a[0,0],a[1,1],a[2,2],a[3,3] # 튜플 => 수정 불가능
print(type(a1))
print(a1)
a2 =[a[0,0],a[1,1],a[2,2],a[3,3]] # 리스트 => 수정 가능
print(type(a2))
print(a2)

1 8 15 22
<class 'tuple'>
(1, 8, 15, 22)
<class 'list'>
[1, 8, 15, 22]


배열 변환  
배열을 변환하는 방법은 전치, 배열 shape변환, 배열 요소 추가, 배열 결합, 배열 분리 등이 있다.

In [21]:
# 전치는 행렬의 인덱스가 바뀌는 것이다.
# 행과 열이 바뀌는 것.
# 넘파이에서 배열을 전치하기 위해 배열이름.T 속성을 사용한다.
a = np.random.randint(1,10,(2,3))
pprint(a)
pprint(a.T) # 이게 전치이다.
# 소문자를 사용하면 에러가 발생한다.

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[1 1 9]
 [3 7 8]]
type: <class 'numpy.ndarray'>
shape: (3, 2), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[1 3]
 [1 7]
 [9 8]]


In [22]:
# 배열 형태 변경
# 넘파이는 배열의 shape을 변경하는 reshape() 함수와 ravel() 함수를 제공한다.
# reshape() 함수는 데이터 변경없이 지정된 shape으로 배열의 형태를 반환한다.
# ravel() 함수는 배열의 shape을 무조건 1차원으로 변환한다.

In [23]:
a = np.random.randint(1,10,(3,4))
pprint(a)
pprint(a.reshape(2,6)) # reshape() 함수로 shape을 변경해서 변수에 저장시켜 사용한다. #reshape()만 하면 view니까
pprint(a.ravel())


type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[2 2 6 1]
 [7 4 3 5]
 [6 2 6 8]]
type: <class 'numpy.ndarray'>
shape: (2, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[2 2 6 1 7 4]
 [3 5 6 2 6 8]]
type: <class 'numpy.ndarray'>
shape: (12,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [2 2 6 1 7 4 3 5 6 2 6 8]


In [24]:
# ravel() 함수도 인덱싱, 슬라이싱의 경우처럼 원본 배열의 view를 보여준다.
# 따라서 , ravel() 함수가 반환한 배열을 수정하면 원본배열의 내용이 같이 수정된다.
# reshape() 또한 마찬가지.
a = np.random.randint(1,10,(3,4))
pprint(a)
b=a.ravel()
pprint(b)
b[0]=9999
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[9 8 9 5]
 [8 1 3 7]
 [3 2 1 2]]
type: <class 'numpy.ndarray'>
shape: (12,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [9 8 9 5 8 1 3 7 3 2 1 2]
type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[9999    8    9    5]
 [   8    1    3    7]
 [   3    2    1    2]]


In [25]:
# resize() 함수는 배열의 shape과 크기를 변경한다.
# np.resize(배열이름, new_shape), 배열이름.resize(new_shape)
# resize() 와 reshape() 함수는 shape을 변경한다는 부분에서는 동일하지만 reshape() 함수는 요소의 개수를 변경하면
# 에러가 발생되는 반면에 resize() 함수는 shape을 변경하는 과정에서 요소의 개수를 늘이거나 줄일 수 있다.


In [26]:
a = np.random.randint(1,10,(3,4))
pprint(a)
np.resize(a,(6,2)) # 얘도 view 따라서 변경한거 사용하려면 새 배열에 저장해야 된다.

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[8 3 5 5]
 [7 6 6 5]
 [8 1 7 8]]


array([[8, 3],
       [5, 5],
       [7, 6],
       [6, 5],
       [8, 1],
       [7, 8]])

In [27]:
# 요소의 개수가 변경되는 resize()
a = np.random.randint(1,10,(2,6))
pprint(a)

# a.reshape(2,10) # reshape() 함수는 원본 요소의 개수와 reshape() 함수로 변경하는 요소의 개수가 다르면 에러가 발생한다.
# np.resize(배열이름, new_shape) 형식은 실행 결과 원본 데이터가 변경되지 않는다. => view다.
# 배열 요소의 개수가 12개 에서 20개로 늘어나고 늘어난 요소에 원본 내용이 반복해서 채워진다.
b= np.resize(a,(2,10)) # 본래는 2,6 = 12 이지만 이번에는 2,10 = 20로 데이터 개수가 다르다.
pprint(b) # 개수가 넘어가는 부분은 다시 처음부터 반복하면서 채운다.

# 배열이름.resize(new_shape) 형식은 실행 결과 원본 데이터가 변경된다. 즉, 다른변수에 넣으면 안된다.
# 배열 요소의 개수가 12개 에서 20개로 늘어나고 늘어난 요소에는 0이 채워진다.
a.resize((2,10))
pprint(a)

type: <class 'numpy.ndarray'>
shape: (2, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[2 6 3 7 7 9]
 [8 5 5 2 6 8]]
type: <class 'numpy.ndarray'>
shape: (2, 10), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[2 6 3 7 7 9 8 5 5 2]
 [6 8 2 6 3 7 7 9 8 5]]
type: <class 'numpy.ndarray'>
shape: (2, 10), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[2 6 3 7 7 9 8 5 5 2]
 [6 8 0 0 0 0 0 0 0 0]]


In [28]:
a = np.random.randint(1,10,(2,6))
pprint(a)

b= np.resize(a,(2,4)) # 배열 요소의 개수가 12개에서 8개로 줄어들고 줄어든 요소의 데이터는 분실된다.
pprint(b)
a.resize(2,4) # 이번에는 두개가 똑같다.
pprint(a)

type: <class 'numpy.ndarray'>
shape: (2, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[3 1 6 6 7 5]
 [4 5 3 9 3 1]]
type: <class 'numpy.ndarray'>
shape: (2, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[3 1 6 6]
 [7 5 4 5]]
type: <class 'numpy.ndarray'>
shape: (2, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[3 1 6 6]
 [7 5 4 5]]


In [29]:
# append() 함수는 배열 끝에 데이터(배열)를 추가한다. axis로 데이터가 추가되는 방향을 지정할 수 있다. axis 안쓰면 None
# np.append(배열이름,추가할데이터,axis)

In [30]:
a = np.random.randint(1,10,(3,3))
pprint(a)
b = np.random.randint(1,10,(3,3))
pprint(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[7 9 4]
 [9 2 1]
 [3 9 2]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[5 9 5]
 [2 5 9]
 [1 9 9]]


In [31]:
# axis를 지정하지 않을 경우(생략하는 경우와 똑같음)
# axis를 지정하지 않으면 배열은 1차원 배열로 변환되서 결합된다.
result = np.append(a, b, axis=None)
pprint(result)

type: <class 'numpy.ndarray'>
shape: (18,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [7 9 4 9 2 1 3 9 2 5 9 5 2 5 9 1 9 9]


In [32]:
# axis = 0으로 지정할 경우
# 배열의 아래쪽에 배열이 추가된다. => 열 방향으로 추가
# 행의 개수는 달라도 상관 없지만 열의 개수는 반드시 같아야 한다!!
result = np.append(a,b,axis=0)
pprint(result)

print(result.shape) # 2차원 배열에서 shape은 행과 열을 의미한다.
print(result.shape[0]) # 2차원 배열에서 shape은 행을 의미한다.
print(result.shape[1]) # 2차원 배열에서 shape은 열을 의미한다.

# axis=0으로 설정시 shape[0]은 서로 달라도 상관없지만 shape[1]은 반드시 같아야 오류가 발생 되지 않는다.

type: <class 'numpy.ndarray'>
shape: (6, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[7 9 4]
 [9 2 1]
 [3 9 2]
 [5 9 5]
 [2 5 9]
 [1 9 9]]
(6, 3)
6
3


In [33]:
# axis = 1으로 지정할 경우
# 배열의 오른쪽에 배열이 추가된다. => 행 방향으로 추가
# 열의 개수는 달라도 상관 없지만 행의 개수는 반드시 같아야 한다!!
result = np.append(a,b,axis=1)
pprint(result)

print(result.shape) # 2차원 배열에서 shape은 행과 열을 의미한다.
print(result.shape[0]) # 2차원 배열에서 shape은 행을 의미한다.
print(result.shape[1]) # 2차원 배열에서 shape은 열을 의미한다.

type: <class 'numpy.ndarray'>
shape: (3, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[7 9 4 5 9 5]
 [9 2 1 2 5 9]
 [3 9 2 1 9 9]]
(3, 6)
3
6


In [34]:
# insert() 함수는 지정된 index 위치에 데이터를 삽입한다. axis로 데이터가 삽입되는 방향을 지정할 수 있다.
# np.insert(배열이름, index, 추가할 데이터, axis)
a = np.arange(1,10).reshape(3,3)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
# axis 지정하지 않으면 1차원으로 바뀌어서 설정한 인덱스에 데이터를 삽입하고 나머지는 뒤로 밀린다
#pprint(np.insert(a,1,99999,axis=None))
pprint(np.insert(a,1,99999))

type: <class 'numpy.ndarray'>
shape: (10,), dimension: 1, dtype: int32
numpy 배열에 저장된 데이터
 [    1 99999     2     3     4     5     6     7     8     9]


In [36]:
# axis=0으로 지정하면 열 방향으로 index가 1인 행에 데이터를 삽입한다.
pprint(np.insert(a,1,99999,axis=0)) # 열방향 인덱스=> 방향이 인덱스가 되는거다. 즉 행=열 방향이니까 세로 방향으로 삽입

type: <class 'numpy.ndarray'>
shape: (4, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[    1     2     3]
 [99999 99999 99999]
 [    4     5     6]
 [    7     8     9]]


In [37]:
# axis=1으로 지정하면 행 방향으로 index가 1인 열에 데이터를 삽입한다.
pprint(np.insert(a,1,99999,axis=1)) # 행방향 인덱스 => 방향이 인덱스가 되는거다. 즉 행 방향이니까 가로 방향으로 삽입

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[    1 99999     2     3]
 [    4 99999     5     6]
 [    7 99999     8     9]]


In [38]:
# delete() 함수는 지정된 index의 데이터를 삭제한다. axis로 데이터가 삭제되는 방향을 지정할 수 있다.
# delete(배열이름, index, axis)
a = np.arange(1,10).reshape(3,3)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
# axis를 지정하지 않았으므로 1차원 배열로 변환하고 1번째 index의 데이터를 삭제한다.
# print(np.delete(a,1, axis=None))
print(np.delete(a,1))

[1 3 4 5 6 7 8 9]


In [40]:
pprint(np.delete(a,1,axis=0)) # 열방향 인덱스 => 방향이 인덱스가 되는거다. 즉 열 방향이니까 위에서 아래 방향에서 1번삭제 

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[1 2 3]
 [7 8 9]]


In [41]:
pprint(np.delete(a,1,axis=1)) # 행방향 인덱스 => 방향이 인덱스가 되는거다. 즉 행 방향이니까 왼쪽에서 오른쪽 방향에서 1번삭제

type: <class 'numpy.ndarray'>
shape: (3, 2), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[1 3]
 [4 6]
 [7 9]]


배열 분리  
numpy는 배열을 수직 방향으로 분할하는 np.vsplit() 함수와 수평 방향으로 분할하는 np.hsplit() 함수를 제공한다.

In [43]:
# np.hsplit() 함수로 배열을 수평 방향으로 분할한다.
# np.hsplit(배열이름, 분할할 배열의 개수)
a= np.arange(1,25).reshape(4,6)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype: int32
numpy 배열에 저장된 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [49]:
result=np.hsplit(a,2) # hsplit() 함수의 실행결과는 파이썬 list이다.
print(type(result)) #--> 이렇게하면 list로 type이 바뀐다. <class 'list'>
print(result)
print(type(result[0])) #<class 'numpy.ndarray'> 즉 하나의 배열안에 split된 numpy배열 2개가 들어가진것.
print(result[0])

<class 'list'>
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
<class 'numpy.ndarray'>
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


In [52]:
result=np.hsplit(a,3)  # a의 g행이
print(type(result))
print(result)
print(type(result[0]))
print(result[0])

<class 'list'>
[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]
<class 'numpy.ndarray'>
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]]


In [53]:
result=np.hsplit(a,[1,2,3]) 
print(type(result)) 
print(result)
print(type(result[0])) 
print(result[0])

<class 'list'>
[array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2],
       [ 8],
       [14],
       [20]]), array([[ 3],
       [ 9],
       [15],
       [21]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])]
<class 'numpy.ndarray'>
[[ 1]
 [ 7]
 [13]
 [19]]


In [ ]:
# np.vsplit() 함수로 배열을 수평 방향으로 분할한다.
# np.vsplit(배열이름, 분할할 배열의 개수)
a= np.arange(1,25).reshape(4,6)
pprint(a)

In [54]:
result=np.vsplit(a,2) 
print(type(result)) 
print(result)
print(type(result[0])) 
print(result[0])

<class 'list'>
[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
<class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
